version: "4.27"
services:
  bot:
    build: .
    command: sh -c "python -m bot"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./.env:/app/.env
    # env_file:
    #   - .env
    restart: always

